fragment MediaFragment on FileField {
	id
	alt
	basename
	format
	mimeType
	size
	title
	url
	width
	height
	responsiveImage {
		...ResponsiveImageFragment
	}
	video {
		thumbnailUrl
		streamingUrl
		mp4Url(res: high)
		mp4high: mp4Url(res: high)
		mp4med: mp4Url(res: medium)
		mp4low: mp4Url(res: low)
		framerate
		duration
	}
}
