query Exhibition {
	exhibition {
		id
		title
		intro {
			links
			value
			blocks
		}
		text {
			links
			value
			blocks
		}
		image {
			...ImageFragment
		}
		logo {
			...ImageFragment
		}
	}
}
