query Start {
	start {
		id
		slideshow {
			__typename
			... on ImageBlockRecord {
				id
				image {
					...ImageFragment
				}
			}
			... on TextBlockRecord {
				id
				text
				smallHeadline
			}
			... on VideoBlockRecord {
				id
				video {
					...VideoFragment
				}
			}
		}
	}
}
