query AllVenues {
	allVenues(orderBy: position_DESC) {
		...VenueFragment
	}
}

query Venue($id: ItemId!) {
	venue(filter: { id: { eq: $id } }) {
		...VenueFragment
	}
}

fragment VenueFragment on VenueRecord {
	id
	city
	openingDates
	venueStatus
	address
	openBetween
	logo {
		...ImageFragment
	}
	text {
		blocks
		value
		links
	}
	media {
		...MediaFragment
	}
}
