query AllVenues {
	allVenues(orderBy: position_DESC) {
		id
		city
		openingDate
		closingDate
		address
		openBetween
		text {
			blocks
			value
			links
		}
		media {
			...MediaFragment
		}
	}
}

query Venue($id: ItemId!) {
	venue(filter: { id: { eq: $id } }) {
		id
		city
		openingDate
		closingDate
		address
		openBetween
		text {
			blocks
			value
			links
		}
		media {
			...MediaFragment
		}
	}
}
